# Generated by Django 4.0.2 on 2022-03-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=70)),
                ('StateId', models.IntegerField()),
                ('CityId', models.IntegerField()),
                ('Pincode', models.IntegerField()),
                ('ContactNumber', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='serviceprovider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=70)),
                ('StateId', models.IntegerField()),
                ('CityId', models.IntegerField()),
                ('UserId', models.IntegerField()),
                ('Pincode', models.IntegerField()),
                ('ContactNumber', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'Service_Provider',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=1)),
                ('Password', models.CharField(max_length=30)),
                ('ContactNummber', models.IntegerField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
