# Generated by Django 4.0.2 on 2022-03-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ContactNummber',
            new_name='ContactNumber',
        ),
    ]
